server:
  port: 8887
spring:
  application:
    name: springcloud-service-config
  cloud:
    config:
      server:
        git:
          # 仓库地址
          uri: https://gitee.com/myiszhb/spring-cloud-remotely-config.git
          # 仓库目录
          search-paths: config-server/goods,config-server/portal
          # 仓库账号
          username: myiszhb@gmail.com
          # 仓库密码
          password: 2020Fate!
    # 开启spring cloud bus，默认开启
    bus:
      enabled: true
  # 配置rabbitmq
  rabbitmq:
    host: 111.231.207.228
    port: 5672
    username: myiszhb
    password: 2020Fate!
  # 配置安全认证
  security:
    user:
      name: myiszhb
      password: 123456
# 打开所有的web访问端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  instance:
    #每间隔2s，向服务端发送一次心跳，证明自己存活
    lease-renewal-interval-in-seconds: 2
    #告诉服务端，如果我10s没有像你发送心跳，就代表我故障了，将我踢掉
    lease-expiration-duration-in-seconds: 10
    #告诉服务端，服务实例以ip作为链接，而不是机器名
    prefer-ip-address: true
    #告诉服务端，服务实例的名称
    instance-id: springcloud-service-config-8887
  client:
    service-url:
      #指定服务注册中心的位置
      defaultZone: http://111.231.207.228:8761/eureka,http://111.231.207.228:8762/eureka,http://111.231.207.228:8763/eureka