server:
  port: 80
spring:
  application:
    name: springcloud-service-zuul
eureka:
  instance:
    #每间隔2s，向服务端发送一次心跳，证明自己存活
    lease-renewal-interval-in-seconds: 2
    #告诉服务端，如果我10s没有像你发送心跳，就代表我故障了，将我踢掉
    lease-expiration-duration-in-seconds: 10
    #告诉服务端，服务实例以ip作为链接，而不是机器名
    prefer-ip-address: true
    #告诉服务端，服务实例的名称
    instance-id: springcloud-service-zuul
  client:
    service-url:
      #指定服务注册中心的位置
      defaultZone: http://111.231.207.228:8761/eureka,http://111.231.207.228:8762/eureka,http://111.231.207.228:8763/eureka

zuul:
  # zuul的超时时间
  host:
    connect-timeout-millis: 5000
  # zuul 路由规则
  routes:
    portal:
      service-id: springcloud-service-protal
      path: /portal/**
  # zuul 忽略某个服务名，禁止通过服务名称调用，*号表示禁止所有服务名调用
  ignored-services: '*'
  #给所有经过zuul网关接口加一个访问权限,比如 http://127.0.0.1/api/portal/service/goodsFeginHystrix
  prefix: /api
  # 禁止访问的路由
  ignored-patterns: /**/feign/**
  #禁用自定义拦截器，LogFilter为拦截器名称
  LogFilter:
    route:
      disable: true
  SendErrorFilter:
    route:
      disable: true